### ISSUE TITLE
Teoria da Blockchain (Bitcoin/Ethereum)

### ISSUE THREAD

**Issue by crissilvaeng** [training-center/blockchain-study-group#1]
Espaço reservado para coleta de links de material de estudos para a primeira iteração de estudos do grupo de Blockchain.

**Quem pode sugerir e votar?**

1. Qualquer membro do grupo pode sugerir material.
2. Qualquer membro do grupo pode votar nos materiais sugeridos.

**Como sugerir um material?**

Cada sugestão de material deve ser postada em um comentário individual nesta issue, os materiais sugeridos devem, obrigatoriamente, conter os campos abaixo: 

Campo | Descrição | Exemplo
--- | --- | ---
Nome | Nome ou titulo do material. | *Bitcoin: A Peer-to-Peer Electronic Cash System*
Tipo | Tipo do material. (livro, blog, curso, etc) | Whitepaper
URL | Local para acesso ou de compra do material. | https://bitcoin.org/bitcoin.pdf
Custo | Informar se o recurso é pago ou gratuito. (`:free:` ou `:moneybag:`) |  :free:
Motivo | Justifique porque o material deveria ser escolhido, qual a relevância dele. | Paper de 2008, descreve o funcionamento da rede Bitcoin e transações sem intermediários.

**Como ocorrem as votações?**

- Para votar positivamente em relação a uma sugestão, deixe um 👍  no comentário.
- Para votar negativamente em relação a uma sugestã0, deixe um 👎 no comentário.

**Qual o período de votação e seleção?**

O material de estudos será escolhido até a próxima quarta-feira, as sugestões mais bem avaliadas serão adicionadas ao roadmap do grupo.

**Informações adicionais:**

1. Clique em _Subscribe_ para garantir notificações a cada nova sugestão postada.
2. Não poste sugestão duplicada.
3. Não se esqueça de votar na sua própria sugestão de material.
3. Entre no canal do Slack: **[\#blockchain-studies](https://ctgroups.slack.com/messages/C8VV5DPUJ/)**
---

**Template para Sugestão**

```
Nome | Titulo do Material
--- | ---
Tipo | (livro, blog, curso, etc)
URL | https://url.do/material
Custo | (`:free:` ou `:moneybag:`)
Motivo | Lorem ipsum.
```

**Comment by crissilvaeng** [comment]
Nome | Bitcoin: A Peer-to-Peer Electronic Cash System
--- | ---
Tipo | Whitepaper
URL | https://bitcoin.org/bitcoin.pdf
Custo | :free:
Motivo | Paper original do Bitcoin, trás pela primeira vez a proposta de uma moeda virtual e da Blockchain.

**Comment by crissilvaeng** [comment]
Nome | A Next-Generation Smart Contract and Decentralized Application Platform
--- | ---
Tipo | Whitepaper
URL | https://github.com/ethereum/wiki/wiki/White-Paper
Custo | :free:
Motivo | Paper original do Ethereum, descreve a plataforma, define contratos inteligentes e exemplifica DApp que poderiam ser desenvolvidas com essa tecnologia.

**Comment by camilaavilarinho** [comment]
Nome | WTF is The Blockchain?
--- | ---
Tipo | Artigo Medium
URL | https://hackernoon.com/wtf-is-the-blockchain-1da89ba19348
Custo | :free:
Motivo | Artigo muito didático explicando como a blockchain funciona

**Comment by camilaavilarinho** [comment]
Nome | Introduction to Bitcoin
--- | ---
Tipo | Vídeo
URL | https://www.youtube.com/watch?v=l1si5ZWLgy0&t=5s&index=1&list=LLt3BQ1nsKsJCbfyPmxucyGQ
Custo | :free:
Motivo | Vídeo do Andreas Antonopoulos, referência por produzir material de muita qualidade e por explicar o assunto de forma simples e entendível

**Comment by crissilvaeng** [comment]
Vamos discutir o roadmap primeiro, em outra issue neste mesmo repositorio. Por esse motivo esta issue fica temporariamente bloqueada.
