### ISSUE TITLE
Issue para discutir o Roadmap

### ISSUE THREAD

**Issue by camilaavilarinho** [training-center/blockchain-study-group#2]
Vamos discutir o roadmap aqui antes de decidir qualquer coisa. 
A ideia é que a gente coloque aqui sugestões de roadmaps e depois junte em um adapatado aos interesses do grupo. 

Acho que podemos seguir o modelo de formatação que a @crissilvaeng sugeriu [aqui](https://github.com/training-center/blockchain-study-group/issues/1)

**Comment by camilaavilarinho** [comment]
Nome | The authoritative guide to blockchain development
--- | ---
Tipo | Artigo Medium
URL | https://medium.freecodecamp.org/the-authoritative-guide-to-blockchain-development-855ab65b58bc
Custo | :free:
Motivo | Roadmap mais completo que eu já encontrei 


* Prerequisites
    * Computer Science
        * Data structures( linked lists, binary search trees, hash maps, and graphs (specifically, directed acyclic graphs )
        * Cryptography(RSA, ECDSA, cryptographic hash function, commitment schemes, Merkle trees, Merkle proofs)
        * Distributed Systems
        * Networking 
        * Economics (Game theory, macroeconomics, microeconomics)
* The theoretical foundations of Bitcoin
    * Bitcoin whitepaper
    * Other materials
    * lecture on Bitcoin mining
    * Bitcoin block header
    * Bitcoin explorer
    * history of Bitcoin and cryptocurrencies
* Building a blockchain yourself
    * Blockchain implementation tutorials
* Ethereum and smart contract programming
    * DAOs
    * Ethereum yellow paper and its internals
    * Solidity (CryptoZombies tutorial)
    * Develop an application 
* Smart contract security
* Taking off the training wheels
    * Solidity development stack
    * Ganache
    * Truffle framework
    * IPFS
* Building your own projects
    * Deploying an end-to-end Dapp

**Comment by camilaavilarinho** [comment]
Nome | Sugestão de um desenvolvedor Blockchain da Deloitte
--- | ---
Tipo | Pergunta no linkedIn
URL | 
Custo | :free:
Motivo | Eu estava perguntando para alguns desenvolvedores sugestões sobre o que estudar


* Basico sobre blockchain
    * Como apareceu (Bitcoin) e como evoluiu (Ethereum)
    * Detalhes da tecnologia
* Como desenvolver aplicações em cima da stack do Ethereum
    * Os básicos sobre transações, e smart contracts
    * Introducao as linguagens (ex. Solidity).
    * Utilizacao de ferramentas (MetaMask, Truffle, Ganache)
* Outras tecnologias
    * Hyperledger, IOTA, Cardano

**Comment by locemarn** [comment]
Nome | Desenvolvimento Blockchain com Ethereum
-- | --
Tipo | Curso Udemy
URL | [Ementa do curso](https://github.com/hernandev/curso-blockchain-ethereum#desenvolvimento-blockchain-com-ethereum)
Custo |  Consultar Diego Hernandes - @hernandev
Motivo | Curso que será vendido na plataforma Udemy com ementa agradável e que podemos mesclar com as outras idéias já citadas para fazermos nosso Roamap. **OBS.:** A sugestão é da ementa.

**Comment by alissonfpmorais** [comment]
Nome | Desenvolvimento Blockchain com Ethereum
-- | --
Tipo | Pontos fundamentais
URL | 
Custo | 🆓 
Motivo | Cada roadmap sugerido possui seus pontos interessantes, então montei um modelo que acredito compilar os pontos principais de cada sugestão.

- Introdução ao Blockchain
  - O que é?
  - História
- Detalhes do Blockchain
  - Quais os diferentes tipos? (construções, comportamentos, proofs, etc)
  - Quais as tecnologias envolvidas? (se necessário podemos aprofundar em algo, de acordo com a necessidade do grupo)
- Cryptocurrencies
  - Bitcoin
  - Ethereum
  - IOTA
  - ...
- Desenvolvimento
  - Plataformas (escolher uma ou mais, como: Ethereum, IOTA, etc)
    - Termos utilizados
    - Configurações iniciais
    - Desenvolvimento
    - Segurança
    - Integração com outras plataformas (backend e frontend)
    - Deploy

**Comment by Diego-Brocanelli** [comment]
Bom dia, essa issue ainda se mostra relevante, ou podemos encera-la?

**Comment by crissilvaeng** [comment]
Ola, @Diego-Brocanelli, acredito que pode encerrar.

**Comment by Diego-Brocanelli** [comment]
@camilaavilarinho podemos encerrar, tendo em vista que você criou a issue?

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno @crissilvaeng

**Comment by camilaavilarinho** [comment]
Sim, pode encerrar @Diego-Brocanelli

**Comment by Diego-Brocanelli** [comment]
Obrigado pelo retorno @camilaavilarinho
